### ISSUE TITLE
"Setup on Bare Metal Linux" issue when running "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by RomTheG** [nuodb/nuodb-collector#23]
Hello,

I am following the installation steps from "Setup on Bare Metal Linux".
I am getting following error when I am running the command "`pip install -r requirements.txt`":

```
Collecting requests>=2.24.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a5/61/a867851fd5ab77277495a8709ddda0861b28163c4613b011bc00228cc724/requests-2.28.1.tar.gz
    Complete output from command python setup.py egg_info:

    ==========================
    Unsupported Python version
    ==========================
    This version of Requests requires at least Python 3.7, but
    you're trying to install it on Python 2.7. To resolve this,
    consider upgrading to a supported Python version.

    If you can't upgrade your Python version, you'll need to
    pin to an older version of Requests (<2.28).

```

It seems that latest releases from "Requests" no more support Python 2.

**Comment by butson** [comment]
This should be addressed with branch dbutson/python3.  which is out for review. 

This change will allow running python2 or python3.  requirements are different depending upon the version of python you wish to use.

**Comment by rshaull** [comment]
Hi @RomTheG , thanks for trying out the install. Please share a few details about your setup with us? What version of python and pip are you using (`python --version` and `pip --version`)?

It looks like you might be running into an issue where pip is erroneously using a cached version of Requests instead of downloading the correct version for Python 2.7.

Please try this command:

`pip install --no-cache-dir -r requirements.txt`

And see if you still get a message like "Using cached ... requests-2.28.1.tar.gz".

**Comment by RomTheG** [comment]
After upgrading PIP to 20.3.4, it works fine.
For the record, I am using Python 2.7.5 and was using out of age PIP 8.1.2
My bad, sorry.

**Comment by rshaull** [comment]
No worries @RomTheG . Glad you got it resolved!
